POST https://node-do-zero-yrkh.onrender.com/videos
Content-type: application/json


{
    "title": "Video 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}


###

GET https://node-do-zero-yrkh.onrender.com/videos


###

PUT https://node-do-zero-yrkh.onrender.com/videos/f7150cd0-7c10-41d0-80b5-ff4d14f02b17
Content-type: application/json


{
    "title": "Video node",
    "description": "Esse é o segundo vídeo",
    "duration": 180
}

###

DELETE https://node-do-zero-yrkh.onrender.com/videos/f7150cd0-7c10-41d0-80b5-ff4d14f02b17
